is-sharding = true
shard-mode = "pessimistic"
online-ddl = true
shadow-table-rules = []
trash-table-rules = []
online-ddl-scheme = ""
case-sensitive = false
collation_compatible = "loose"
name = "test"
mode = "all"
ignore-checking-items = []
source-id = "mysql-replica-01"
server-id = 0
flavor = ""
meta-schema = "dm_meta"
heartbeat-update-interval = 0
heartbeat-report-interval = 0
enable-heartbeat = false
timezone = ""
relay-dir = ""
use-relay = false
expression-filter = []
mydumper-path = "./bin/mydumper"
threads = 4
chunk-filesize = "64"
statement-size = 0
rows = 0
where = ""
skip-tz-utc = true
extra-args = ""
pool-size = 16
dir = "./dumped_data"
import-mode = "sql"
on-duplicate = "replace"
meta-file = ""
worker-count = 16
batch = 100
queue-size = 1024
checkpoint-flush-interval = 1
compact = true
multiple-rows = true
max-retry = 0
auto-fix-gtid = false
enable-gtid = false
disable-detect = false
safe-mode = false
enable-ansi-quotes = false
log-level = ""
log-file = ""
log-format = ""
log-rotate = ""
pprof-addr = ""
status-addr = ""
clean-dump-file = false
ansi-quotes = false

[from]
  host = "127.0.0.1"
  port = 3306
  user = "root"
  password = "******"
  [from.session]

[to]
  host = "127.0.0.1"
  port = 4000
  user = "root"
  password = "******"
  [to.session]
    tidb_txn_mode = "optimistic"

[[route-rules]]
  schema-pattern = "dmctl"
  table-pattern = "t_*"
  target-schema = "dmctl"
  target-table = "t_target"

[[route-rules]]
  schema-pattern = "dmctl"
  table-pattern = ""
  target-schema = "dmctl"
  target-table = ""

[[filter-rules]]
  schema-pattern = "dmctl"
  table-pattern = "t_1"
  events = ["all"]
  sql-pattern = []
  action = "Do"

[[mapping-rule]]
  schema-pattern = "dmctl"
  table-pattern = "t_*"
  source-column = "id"
  target-column = "id"
  expression = "partition id"
  arguments = ["1", "", "t_", ""]
  create-table-query = ""

[ValidatorCfg]
  mode = ""
  worker-count = 0

[experimental]
  async-checkpoint-flush = false
