
- name: Create data dir
  file: path={{ df_data_prefix }} owner=root group=root state=directory

- name: Create bin dir
  file: path={{ df_bin_dir }} owner=root group=root state=directory

- name: Create script dir
  file: path={{ df_script_dir }} owner=root group=root state=directory

- name: Copy bins
  copy: src={{ item }} dest={{ df_bin_dir }} mode=0655
  loop:
    - master
    - executor
