version: '2.1'

orbs:
  codecov: codecov/codecov@3.1.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.16

    steps:
      - checkout
      - run:
        name: Do check
        command: make check
      - run:
        name: Build
        command: make
      - run:
        name: Run ut
        command: make unit_test
      - codecov/upload:
        file: /tmp/dataflow_engine_test/cov.unit.out

workflows:
  version: 2.1
  build-workflow:
    jobs:
      - build
