version: '2.3'

services:
  frame_etcd_standalone:
    image: quay.io/coreos/etcd
    container_name: frame_etcd_standalone
    command: etcd -name frame_etcd_standalone -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "frame_etcd_standalone=http://frame_etcd_standalone:2380" -initial-cluster-state new
    ports:
      - "12379:2379"
      - "12380:2380"
  user_etcd_standalone:
    image: quay.io/coreos/etcd
    container_name: user_etcd_standalone
    command: etcd -name user_etcd_standalone -advertise-client-urls http://0.0.0.0:2479 -listen-client-urls http://0.0.0.0:2479 -listen-peer-urls http://0.0.0.0:2480 -initial-cluster-token etcd-cluster -initial-cluster "user_etcd_standalone=http://user_etcd_standalone:2480" -initial-cluster-state new
    ports:
      - "12479:2479"
      - "12480:2480"
