version: "2.3"
services:
        server-master-0:
                image: dataflow:test
                volumes:
                        - ./config/master.toml:/config.toml
                        - /tmp/df:/tmp/df
                command:
                        - "./bin/master"
                        - "--config"
                        - "/config.toml"
                        - "--master-addr"
                        - "0.0.0.0:10240"
                        - "--advertise-addr"
                        - "server-master-0:10240"
                        - "--peer-urls"
                        - "http://127.0.0.1:8291"
                        - "--advertise-peer-urls"
                        - "http://server-master-0:8291"
                        - "--initial-cluster"
                        - "http://server-master-0:8291,http://server-master-1:8291,http://server-master-2:8291"
        server-master-1:
                image: dataflow:test
                volumes:
                        - ./config/master.toml:/config.toml
                        - /tmp/df:/tmp/df
                command:
                        - "./bin/master"
                        - "--config"
                        - "/config.toml"
                        - "--master-addr"
                        - "0.0.0.0:10240"
                        - "--advertise-addr"
                        - "server-master-1:10240"
                        - "--peer-urls"
                        - "http://127.0.0.1:8291"
                        - "--advertise-peer-urls"
                        - "http://server-master-1:8291"
                        - "--initial-cluster"
                        - "http://server-master-0:8291,http://server-master-1:8291,http://server-master-2:8291"
        server-master-2:
                image: dataflow:test
                volumes:
                        - ./config/master.toml:/config.toml
                        - /tmp/df:/tmp/df
                command:
                        - "./bin/master"
                        - "--config"
                        - "/config.toml"
                        - "--master-addr"
                        - "0.0.0.0:10240"
                        - "--advertise-addr"
                        - "server-master-2:10240"
                        - "--peer-urls"
                        - "http://127.0.0.1:8291"
                        - "--advertise-peer-urls"
                        - "http://server-master-2:8291"
                        - "--initial-cluster"
                        - "http://server-master-0:8291,http://server-master-1:8291,http://server-master-2:8291"
        server-executor-0:
                image: dataflow:test
                volumes:
                        - ./config/executor.toml:/config.toml
                        - /tmp/dataflow:/tmp/dataflow
                command:
                        - "./bin/executor"
                        - "--config"
                        - "/config.toml"
                        - "--join"
                        - "server-master-0:10240,server-master-1:10240,server-master-2:10240"
                        - "--worker-addr"
                        - "0.0.0.0:10241"
                        - "--advertise-addr"
                        - "server-executor-0:10241"
                depends_on:
                        - "server-master-0"
                        - "server-master-2"
                        - "server-master-1"
                restart: "on-failure"
        server-executor-1:
                image: dataflow:test
                volumes:
                        - ./config/executor.toml:/config.toml
                        - /tmp/dataflow:/tmp/dataflow
                command:
                        - "./bin/executor"
                        - "--config"
                        - "/config.toml"
                        - "--join"
                        - "server-master-0:10240,server-master-1:10240,server-master-2:10240"
                        - "--worker-addr"
                        - "0.0.0.0:10241"
                        - "--advertise-addr"
                        - "server-executor-1:10241"
                depends_on:
                        - "server-master-0"
                        - "server-master-2"
                        - "server-master-1"
                restart: "on-failure"
        server-executor-2:
                image: dataflow:test
                volumes:
                        - ./config/executor.toml:/config.toml
                        - /tmp/dataflow:/tmp/dataflow
                command:
                        - "./bin/executor"
                        - "--config"
                        - "/config.toml"
                        - "--join"
                        - "server-master-0:10240,server-master-1:10240,server-master-2:10240"
                        - "--worker-addr"
                        - "0.0.0.0:10241"
                        - "--advertise-addr"
                        - "server-executor-2:10241"
                depends_on:
                        - "server-master-0"
                        - "server-master-2"
                        - "server-master-1"
                restart: "on-failure"
