// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: master.proto

package pb

import (
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_None      ErrorCode = 0
	ErrorCode_NotLeader ErrorCode = 1
	ErrorCode_Other     ErrorCode = 2
)

var ErrorCode_name = map[int32]string{
	0: "None",
	1: "NotLeader",
	2: "Other",
}

var ErrorCode_value = map[string]int32{
	"None":      0,
	"NotLeader": 1,
	"Other":     2,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{0}
}

// For compatibility, we still use config file to present a job.
type SubmitJobRequest_JobType int32

const (
	SubmitJobRequest_DM        SubmitJobRequest_JobType = 0
	SubmitJobRequest_CDC       SubmitJobRequest_JobType = 1
	SubmitJobRequest_Benchmark SubmitJobRequest_JobType = 2
)

var SubmitJobRequest_JobType_name = map[int32]string{
	0: "DM",
	1: "CDC",
	2: "Benchmark",
}

var SubmitJobRequest_JobType_value = map[string]int32{
	"DM":        0,
	"CDC":       1,
	"Benchmark": 2,
}

func (x SubmitJobRequest_JobType) String() string {
	return proto.EnumName(SubmitJobRequest_JobType_name, int32(x))
}

func (SubmitJobRequest_JobType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{0, 0}
}

type SubmitJobRequest struct {
	Tp     SubmitJobRequest_JobType `protobuf:"varint,1,opt,name=tp,proto3,enum=pb.SubmitJobRequest_JobType" json:"tp,omitempty"`
	Config string                   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	// User name, token, etc...
	User string `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
}

func (m *SubmitJobRequest) Reset()         { *m = SubmitJobRequest{} }
func (m *SubmitJobRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitJobRequest) ProtoMessage()    {}
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{0}
}
func (m *SubmitJobRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubmitJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubmitJobRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubmitJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitJobRequest.Merge(m, src)
}
func (m *SubmitJobRequest) XXX_Size() int {
	return m.Size()
}
func (m *SubmitJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitJobRequest proto.InternalMessageInfo

func (m *SubmitJobRequest) GetTp() SubmitJobRequest_JobType {
	if m != nil {
		return m.Tp
	}
	return SubmitJobRequest_DM
}

func (m *SubmitJobRequest) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

func (m *SubmitJobRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type SubmitJobResponse struct {
	Err        ErrorCode `protobuf:"varint,1,opt,name=err,proto3,enum=pb.ErrorCode" json:"err,omitempty"`
	ErrMessage string    `protobuf:"bytes,2,opt,name=err_message,json=errMessage,proto3" json:"err_message,omitempty"`
}

func (m *SubmitJobResponse) Reset()         { *m = SubmitJobResponse{} }
func (m *SubmitJobResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitJobResponse) ProtoMessage()    {}
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{1}
}
func (m *SubmitJobResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubmitJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubmitJobResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubmitJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitJobResponse.Merge(m, src)
}
func (m *SubmitJobResponse) XXX_Size() int {
	return m.Size()
}
func (m *SubmitJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitJobResponse proto.InternalMessageInfo

func (m *SubmitJobResponse) GetErr() ErrorCode {
	if m != nil {
		return m.Err
	}
	return ErrorCode_None
}

func (m *SubmitJobResponse) GetErrMessage() string {
	if m != nil {
		return m.ErrMessage
	}
	return ""
}

type RegisterExecutorRequest struct {
	// dm need 'worker-name' to locate the worker.
	// TODO: Do we really need a "worker name"? Can we use address to identify an executor?
	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address    string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Version    string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Capability int64  `protobuf:"varint,4,opt,name=capability,proto3" json:"capability,omitempty"`
}

func (m *RegisterExecutorRequest) Reset()         { *m = RegisterExecutorRequest{} }
func (m *RegisterExecutorRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterExecutorRequest) ProtoMessage()    {}
func (*RegisterExecutorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{2}
}
func (m *RegisterExecutorRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegisterExecutorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegisterExecutorRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegisterExecutorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterExecutorRequest.Merge(m, src)
}
func (m *RegisterExecutorRequest) XXX_Size() int {
	return m.Size()
}
func (m *RegisterExecutorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterExecutorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterExecutorRequest proto.InternalMessageInfo

func (m *RegisterExecutorRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterExecutorRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RegisterExecutorRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *RegisterExecutorRequest) GetCapability() int64 {
	if m != nil {
		return m.Capability
	}
	return 0
}

type RegisterExecutorResponse struct {
	Err        ErrorCode `protobuf:"varint,1,opt,name=err,proto3,enum=pb.ErrorCode" json:"err,omitempty"`
	ErrMessage string    `protobuf:"bytes,2,opt,name=err_message,json=errMessage,proto3" json:"err_message,omitempty"`
}

func (m *RegisterExecutorResponse) Reset()         { *m = RegisterExecutorResponse{} }
func (m *RegisterExecutorResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterExecutorResponse) ProtoMessage()    {}
func (*RegisterExecutorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9c348dec43a6705, []int{3}
}
func (m *RegisterExecutorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegisterExecutorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegisterExecutorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegisterExecutorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterExecutorResponse.Merge(m, src)
}
func (m *RegisterExecutorResponse) XXX_Size() int {
	return m.Size()
}
func (m *RegisterExecutorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterExecutorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterExecutorResponse proto.InternalMessageInfo

func (m *RegisterExecutorResponse) GetErr() ErrorCode {
	if m != nil {
		return m.Err
	}
	return ErrorCode_None
}

func (m *RegisterExecutorResponse) GetErrMessage() string {
	if m != nil {
		return m.ErrMessage
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterEnum("pb.SubmitJobRequest_JobType", SubmitJobRequest_JobType_name, SubmitJobRequest_JobType_value)
	proto.RegisterType((*SubmitJobRequest)(nil), "pb.SubmitJobRequest")
	proto.RegisterType((*SubmitJobResponse)(nil), "pb.SubmitJobResponse")
	proto.RegisterType((*RegisterExecutorRequest)(nil), "pb.RegisterExecutorRequest")
	proto.RegisterType((*RegisterExecutorResponse)(nil), "pb.RegisterExecutorResponse")
}

func init() { proto.RegisterFile("master.proto", fileDescriptor_f9c348dec43a6705) }

var fileDescriptor_f9c348dec43a6705 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xbd, 0x4e, 0x48, 0xf0, 0x40, 0xd1, 0x32, 0xe2, 0x8f, 0x55, 0x2a, 0x37, 0xf2, 0x29,
	0x20, 0x14, 0xa4, 0x72, 0xe3, 0xd8, 0xb4, 0x97, 0x8a, 0xb4, 0x92, 0x81, 0x1b, 0x12, 0x5a, 0xdb,
	0x43, 0x6a, 0x81, 0xbd, 0xcb, 0xec, 0x1a, 0xd1, 0x23, 0x6f, 0xc0, 0x05, 0xf1, 0x4a, 0x1c, 0x7b,
	0xe4, 0x88, 0x92, 0x17, 0x41, 0x76, 0xed, 0xaa, 0x0a, 0xe5, 0xc6, 0x6d, 0xe6, 0x1b, 0xcf, 0xf8,
	0xf7, 0xcd, 0x0e, 0xdc, 0x2e, 0x95, 0x75, 0xc4, 0x33, 0xc3, 0xda, 0x69, 0xf4, 0x4d, 0x1a, 0xff,
	0x10, 0x20, 0x5f, 0xd5, 0x69, 0x59, 0xb8, 0x23, 0x9d, 0x26, 0xf4, 0xa9, 0x26, 0xeb, 0xf0, 0x29,
	0xf8, 0xce, 0x84, 0x62, 0x22, 0xa6, 0x77, 0xf6, 0x76, 0x66, 0x26, 0x9d, 0x6d, 0x7e, 0x31, 0x3b,
	0xd2, 0xe9, 0xeb, 0x33, 0x43, 0x89, 0xef, 0x0c, 0x3e, 0x80, 0x51, 0xa6, 0xab, 0xf7, 0xc5, 0x32,
	0xf4, 0x27, 0x62, 0x1a, 0x24, 0x5d, 0x86, 0x08, 0xc3, 0xda, 0x12, 0x87, 0x83, 0x56, 0x6d, 0xe3,
	0xf8, 0x31, 0x8c, 0xbb, 0x56, 0x1c, 0x81, 0x7f, 0xb0, 0x90, 0x1e, 0x8e, 0x61, 0x30, 0x3f, 0x98,
	0x4b, 0x81, 0x5b, 0x10, 0xec, 0x53, 0x95, 0x9d, 0x96, 0x8a, 0x3f, 0x48, 0x3f, 0x7e, 0x03, 0x77,
	0xaf, 0xfc, 0xd6, 0x1a, 0x5d, 0x59, 0xc2, 0x5d, 0x18, 0x10, 0x73, 0x87, 0xb6, 0xd5, 0xa0, 0x1d,
	0x32, 0x6b, 0x9e, 0xeb, 0x9c, 0x92, 0xa6, 0x82, 0xbb, 0x70, 0x8b, 0x98, 0xdf, 0x95, 0x64, 0xad,
	0x5a, 0x52, 0x47, 0x04, 0xc4, 0xbc, 0xb8, 0x50, 0xe2, 0xaf, 0x02, 0x1e, 0x26, 0xb4, 0x2c, 0x9a,
	0x3d, 0x1c, 0x7e, 0xa1, 0xac, 0x76, 0x9a, 0x7b, 0xdf, 0x08, 0xc3, 0x4a, 0x95, 0xd4, 0x8e, 0x0f,
	0x92, 0x36, 0xc6, 0x10, 0xc6, 0x2a, 0xcf, 0x99, 0xac, 0xed, 0x86, 0xf5, 0x69, 0x53, 0xf9, 0x4c,
	0x6c, 0x0b, 0x5d, 0x75, 0x16, 0xfb, 0x14, 0x23, 0x80, 0x4c, 0x19, 0x95, 0x16, 0x1f, 0x0b, 0x77,
	0x16, 0x0e, 0x27, 0x62, 0x3a, 0x48, 0xae, 0x28, 0xf1, 0x5b, 0x08, 0xff, 0x46, 0xf8, 0x5f, 0x0e,
	0x9f, 0x3c, 0x83, 0xe0, 0xb2, 0x05, 0x6f, 0xc2, 0xf0, 0x58, 0x57, 0x24, 0xbd, 0x66, 0xbd, 0xc7,
	0xda, 0xbd, 0x24, 0x95, 0x13, 0x4b, 0x81, 0x01, 0xdc, 0x38, 0x71, 0xa7, 0xc4, 0xd2, 0xdf, 0xfb,
	0x2e, 0x60, 0xb4, 0x68, 0x0f, 0x03, 0x4f, 0x40, 0x6e, 0x92, 0xe1, 0xa3, 0x06, 0xe2, 0x1f, 0x2b,
	0xdb, 0xde, 0xb9, 0xbe, 0x78, 0x61, 0x26, 0xf6, 0xf0, 0x05, 0x04, 0x97, 0xaf, 0x88, 0xf7, 0xae,
	0xbb, 0xa5, 0xed, 0xfb, 0x1b, 0x6a, 0xdf, 0xbb, 0x1f, 0xfe, 0x5c, 0x45, 0xe2, 0x7c, 0x15, 0x89,
	0xdf, 0xab, 0x48, 0x7c, 0x5b, 0x47, 0xde, 0xf9, 0x3a, 0xf2, 0x7e, 0xad, 0x23, 0x2f, 0x1d, 0xb5,
	0x07, 0xfc, 0xfc, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x74, 0x53, 0xfe, 0xb2, 0xd0, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MasterClient is the client API for Master service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MasterClient interface {
	RegisterExecutor(ctx context.Context, in *RegisterExecutorRequest, opts ...grpc.CallOption) (*RegisterExecutorResponse, error)
	SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error)
}

type masterClient struct {
	cc *grpc.ClientConn
}

func NewMasterClient(cc *grpc.ClientConn) MasterClient {
	return &masterClient{cc}
}

func (c *masterClient) RegisterExecutor(ctx context.Context, in *RegisterExecutorRequest, opts ...grpc.CallOption) (*RegisterExecutorResponse, error) {
	out := new(RegisterExecutorResponse)
	err := c.cc.Invoke(ctx, "/pb.Master/RegisterExecutor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) SubmitJob(ctx context.Context, in *SubmitJobRequest, opts ...grpc.CallOption) (*SubmitJobResponse, error) {
	out := new(SubmitJobResponse)
	err := c.cc.Invoke(ctx, "/pb.Master/SubmitJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServer is the server API for Master service.
type MasterServer interface {
	RegisterExecutor(context.Context, *RegisterExecutorRequest) (*RegisterExecutorResponse, error)
	SubmitJob(context.Context, *SubmitJobRequest) (*SubmitJobResponse, error)
}

// UnimplementedMasterServer can be embedded to have forward compatible implementations.
type UnimplementedMasterServer struct {
}

func (*UnimplementedMasterServer) RegisterExecutor(ctx context.Context, req *RegisterExecutorRequest) (*RegisterExecutorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterExecutor not implemented")
}
func (*UnimplementedMasterServer) SubmitJob(ctx context.Context, req *SubmitJobRequest) (*SubmitJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitJob not implemented")
}

func RegisterMasterServer(s *grpc.Server, srv MasterServer) {
	s.RegisterService(&_Master_serviceDesc, srv)
}

func _Master_RegisterExecutor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterExecutorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).RegisterExecutor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Master/RegisterExecutor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).RegisterExecutor(ctx, req.(*RegisterExecutorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Master/SubmitJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).SubmitJob(ctx, req.(*SubmitJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Master_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Master",
	HandlerType: (*MasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterExecutor",
			Handler:    _Master_RegisterExecutor_Handler,
		},
		{
			MethodName: "SubmitJob",
			Handler:    _Master_SubmitJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master.proto",
}

func (m *SubmitJobRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubmitJobRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubmitJobRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.User) > 0 {
		i -= len(m.User)
		copy(dAtA[i:], m.User)
		i = encodeVarintMaster(dAtA, i, uint64(len(m.User)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Config) > 0 {
		i -= len(m.Config)
		copy(dAtA[i:], m.Config)
		i = encodeVarintMaster(dAtA, i, uint64(len(m.Config)))
		i--
		dAtA[i] = 0x12
	}
	if m.Tp != 0 {
		i = encodeVarintMaster(dAtA, i, uint64(m.Tp))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SubmitJobResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubmitJobResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubmitJobResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ErrMessage) > 0 {
		i -= len(m.ErrMessage)
		copy(dAtA[i:], m.ErrMessage)
		i = encodeVarintMaster(dAtA, i, uint64(len(m.ErrMessage)))
		i--
		dAtA[i] = 0x12
	}
	if m.Err != 0 {
		i = encodeVarintMaster(dAtA, i, uint64(m.Err))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RegisterExecutorRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisterExecutorRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegisterExecutorRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Capability != 0 {
		i = encodeVarintMaster(dAtA, i, uint64(m.Capability))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintMaster(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintMaster(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintMaster(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RegisterExecutorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisterExecutorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegisterExecutorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ErrMessage) > 0 {
		i -= len(m.ErrMessage)
		copy(dAtA[i:], m.ErrMessage)
		i = encodeVarintMaster(dAtA, i, uint64(len(m.ErrMessage)))
		i--
		dAtA[i] = 0x12
	}
	if m.Err != 0 {
		i = encodeVarintMaster(dAtA, i, uint64(m.Err))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMaster(dAtA []byte, offset int, v uint64) int {
	offset -= sovMaster(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SubmitJobRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Tp != 0 {
		n += 1 + sovMaster(uint64(m.Tp))
	}
	l = len(m.Config)
	if l > 0 {
		n += 1 + l + sovMaster(uint64(l))
	}
	l = len(m.User)
	if l > 0 {
		n += 1 + l + sovMaster(uint64(l))
	}
	return n
}

func (m *SubmitJobResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Err != 0 {
		n += 1 + sovMaster(uint64(m.Err))
	}
	l = len(m.ErrMessage)
	if l > 0 {
		n += 1 + l + sovMaster(uint64(l))
	}
	return n
}

func (m *RegisterExecutorRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovMaster(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovMaster(uint64(l))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovMaster(uint64(l))
	}
	if m.Capability != 0 {
		n += 1 + sovMaster(uint64(m.Capability))
	}
	return n
}

func (m *RegisterExecutorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Err != 0 {
		n += 1 + sovMaster(uint64(m.Err))
	}
	l = len(m.ErrMessage)
	if l > 0 {
		n += 1 + l + sovMaster(uint64(l))
	}
	return n
}

func sovMaster(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMaster(x uint64) (n int) {
	return sovMaster(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SubmitJobRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMaster
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubmitJobRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubmitJobRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tp", wireType)
			}
			m.Tp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tp |= SubmitJobRequest_JobType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Config", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMaster
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Config = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMaster
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMaster(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMaster
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubmitJobResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMaster
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubmitJobResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubmitJobResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Err", wireType)
			}
			m.Err = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Err |= ErrorCode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrMessage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMaster
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrMessage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMaster(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMaster
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RegisterExecutorRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMaster
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisterExecutorRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisterExecutorRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMaster
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMaster
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMaster
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Capability", wireType)
			}
			m.Capability = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Capability |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMaster(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMaster
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RegisterExecutorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMaster
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisterExecutorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisterExecutorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Err", wireType)
			}
			m.Err = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Err |= ErrorCode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ErrMessage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMaster
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMaster
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ErrMessage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMaster(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMaster
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMaster(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMaster
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMaster
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMaster
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMaster
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMaster
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMaster        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMaster          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMaster = fmt.Errorf("proto: unexpected end of group")
)
