// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: test.proto

package pb

import (
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Record_RecordType int32

const (
	Record_Data Record_RecordType = 0
	Record_DDL  Record_RecordType = 1
)

var Record_RecordType_name = map[int32]string{
	0: "Data",
	1: "DDL",
}

var Record_RecordType_value = map[string]int32{
	"Data": 0,
	"DDL":  1,
}

func (x Record_RecordType) String() string {
	return proto.EnumName(Record_RecordType_name, int32(x))
}

func (Record_RecordType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0, 0}
}

type Record struct {
	Tp        Record_RecordType `protobuf:"varint,1,opt,name=tp,proto3,enum=pb.Record_RecordType" json:"tp,omitempty"`
	SchemaVer int32             `protobuf:"varint,2,opt,name=schema_ver,json=schemaVer,proto3" json:"schema_ver,omitempty"`
	Tid       int32             `protobuf:"varint,3,opt,name=tid,proto3" json:"tid,omitempty"`
	Gtid      int32             `protobuf:"varint,4,opt,name=gtid,proto3" json:"gtid,omitempty"`
	Pk        int32             `protobuf:"varint,5,opt,name=pk,proto3" json:"pk,omitempty"`
	// for record time
	StartTs int64 `protobuf:"varint,6,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	// error
	Err *Error `protobuf:"bytes,7,opt,name=err,proto3" json:"err,omitempty"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}
func (m *Record) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Record.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return m.Size()
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetTp() Record_RecordType {
	if m != nil {
		return m.Tp
	}
	return Record_Data
}

func (m *Record) GetSchemaVer() int32 {
	if m != nil {
		return m.SchemaVer
	}
	return 0
}

func (m *Record) GetTid() int32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *Record) GetGtid() int32 {
	if m != nil {
		return m.Gtid
	}
	return 0
}

func (m *Record) GetPk() int32 {
	if m != nil {
		return m.Pk
	}
	return 0
}

func (m *Record) GetStartTs() int64 {
	if m != nil {
		return m.StartTs
	}
	return 0
}

func (m *Record) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type TestBinlogRequest struct {
	Gtid int32 `protobuf:"varint,1,opt,name=gtid,proto3" json:"gtid,omitempty"`
}

func (m *TestBinlogRequest) Reset()         { *m = TestBinlogRequest{} }
func (m *TestBinlogRequest) String() string { return proto.CompactTextString(m) }
func (*TestBinlogRequest) ProtoMessage()    {}
func (*TestBinlogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}
func (m *TestBinlogRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TestBinlogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TestBinlogRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TestBinlogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestBinlogRequest.Merge(m, src)
}
func (m *TestBinlogRequest) XXX_Size() int {
	return m.Size()
}
func (m *TestBinlogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TestBinlogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TestBinlogRequest proto.InternalMessageInfo

func (m *TestBinlogRequest) GetGtid() int32 {
	if m != nil {
		return m.Gtid
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb.Record_RecordType", Record_RecordType_name, Record_RecordType_value)
	proto.RegisterType((*Record)(nil), "pb.Record")
	proto.RegisterType((*TestBinlogRequest)(nil), "pb.TestBinlogRequest")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x4d, 0x4a, 0x33, 0x41,
	0x10, 0x86, 0xa7, 0x66, 0xf2, 0x5b, 0x81, 0x90, 0xaf, 0xe0, 0x83, 0x36, 0xe2, 0x38, 0x04, 0xc4,
	0x59, 0x05, 0x8d, 0x17, 0x90, 0x10, 0x5d, 0xb9, 0x1a, 0x83, 0xdb, 0x30, 0x49, 0x8a, 0x18, 0xa2,
	0x4e, 0xdb, 0x5d, 0x06, 0xbc, 0x85, 0xc7, 0x72, 0x99, 0xa5, 0x1b, 0x41, 0x92, 0x8b, 0x48, 0xf7,
	0x88, 0x59, 0xb8, 0xea, 0xb7, 0x1f, 0xaa, 0x8a, 0x87, 0x17, 0x51, 0xd8, 0x4a, 0x5f, 0x9b, 0x42,
	0x0a, 0x0a, 0xf5, 0xb4, 0xdb, 0x62, 0x63, 0x0a, 0x53, 0x82, 0xde, 0x27, 0x60, 0x2d, 0xe3, 0x59,
	0x61, 0xe6, 0x74, 0x82, 0xa1, 0x68, 0x05, 0x09, 0xa4, 0xed, 0xc1, 0xff, 0xbe, 0x9e, 0xf6, 0x4b,
	0xfe, 0xf3, 0x8c, 0x5f, 0x35, 0x67, 0xa1, 0x68, 0x3a, 0x42, 0xb4, 0xb3, 0x7b, 0x7e, 0xcc, 0x27,
	0x6b, 0x36, 0x2a, 0x4c, 0x20, 0xad, 0x66, 0xcd, 0x92, 0xdc, 0xb1, 0xa1, 0x0e, 0x46, 0xb2, 0x9c,
	0xab, 0xc8, 0x73, 0x17, 0x89, 0xb0, 0xb2, 0x70, 0xa8, 0xe2, 0x91, 0xcf, 0xd4, 0xc6, 0x50, 0xaf,
	0x54, 0xd5, 0x93, 0x50, 0xaf, 0xe8, 0x00, 0x1b, 0x56, 0x72, 0x23, 0x13, 0xb1, 0xaa, 0x96, 0x40,
	0x1a, 0x65, 0x75, 0xff, 0x1f, 0x5b, 0x3a, 0xc4, 0x88, 0x8d, 0x51, 0xf5, 0x04, 0xd2, 0xd6, 0xa0,
	0xe9, 0xbc, 0xae, 0x9c, 0x7f, 0xe6, 0x68, 0xef, 0x18, 0x71, 0xaf, 0x47, 0x0d, 0xac, 0x8c, 0x72,
	0xc9, 0x3b, 0x01, 0xd5, 0x31, 0x1a, 0x8d, 0x6e, 0x3a, 0xd0, 0x3b, 0xc5, 0x7f, 0x63, 0xb6, 0x32,
	0x5c, 0x3e, 0x3d, 0x14, 0x8b, 0x8c, 0x9f, 0x5f, 0xd8, 0xca, 0xaf, 0x11, 0xec, 0x8d, 0x06, 0x97,
	0xd8, 0x72, 0x83, 0xb7, 0x6c, 0xd6, 0xcb, 0x19, 0xd3, 0x39, 0xe2, 0x35, 0xf3, 0xbc, 0xdc, 0x23,
	0x5f, 0xc7, 0x9f, 0x3b, 0x5d, 0xdc, 0xb7, 0x74, 0x06, 0x43, 0xf5, 0xbe, 0x8d, 0x61, 0xb3, 0x8d,
	0xe1, 0x6b, 0x1b, 0xc3, 0xdb, 0x2e, 0x0e, 0x36, 0xbb, 0x38, 0xf8, 0xd8, 0xc5, 0xc1, 0xb4, 0xe6,
	0xbb, 0xbe, 0xf8, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xfe, 0xde, 0x0f, 0x8a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestServiceClient interface {
	FeedBinlog(ctx context.Context, in *TestBinlogRequest, opts ...grpc.CallOption) (TestService_FeedBinlogClient, error)
}

type testServiceClient struct {
	cc *grpc.ClientConn
}

func NewTestServiceClient(cc *grpc.ClientConn) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) FeedBinlog(ctx context.Context, in *TestBinlogRequest, opts ...grpc.CallOption) (TestService_FeedBinlogClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TestService_serviceDesc.Streams[0], "/pb.TestService/FeedBinlog", opts...)
	if err != nil {
		return nil, err
	}
	x := &testServiceFeedBinlogClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TestService_FeedBinlogClient interface {
	Recv() (*Record, error)
	grpc.ClientStream
}

type testServiceFeedBinlogClient struct {
	grpc.ClientStream
}

func (x *testServiceFeedBinlogClient) Recv() (*Record, error) {
	m := new(Record)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TestServiceServer is the server API for TestService service.
type TestServiceServer interface {
	FeedBinlog(*TestBinlogRequest, TestService_FeedBinlogServer) error
}

// UnimplementedTestServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTestServiceServer struct {
}

func (*UnimplementedTestServiceServer) FeedBinlog(req *TestBinlogRequest, srv TestService_FeedBinlogServer) error {
	return status.Errorf(codes.Unimplemented, "method FeedBinlog not implemented")
}

func RegisterTestServiceServer(s *grpc.Server, srv TestServiceServer) {
	s.RegisterService(&_TestService_serviceDesc, srv)
}

func _TestService_FeedBinlog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TestBinlogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestServiceServer).FeedBinlog(m, &testServiceFeedBinlogServer{stream})
}

type TestService_FeedBinlogServer interface {
	Send(*Record) error
	grpc.ServerStream
}

type testServiceFeedBinlogServer struct {
	grpc.ServerStream
}

func (x *testServiceFeedBinlogServer) Send(m *Record) error {
	return x.ServerStream.SendMsg(m)
}

var _TestService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FeedBinlog",
			Handler:       _TestService_FeedBinlog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "test.proto",
}

func (m *Record) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Record) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Record) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Err != nil {
		{
			size, err := m.Err.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTest(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.StartTs != 0 {
		i = encodeVarintTest(dAtA, i, uint64(m.StartTs))
		i--
		dAtA[i] = 0x30
	}
	if m.Pk != 0 {
		i = encodeVarintTest(dAtA, i, uint64(m.Pk))
		i--
		dAtA[i] = 0x28
	}
	if m.Gtid != 0 {
		i = encodeVarintTest(dAtA, i, uint64(m.Gtid))
		i--
		dAtA[i] = 0x20
	}
	if m.Tid != 0 {
		i = encodeVarintTest(dAtA, i, uint64(m.Tid))
		i--
		dAtA[i] = 0x18
	}
	if m.SchemaVer != 0 {
		i = encodeVarintTest(dAtA, i, uint64(m.SchemaVer))
		i--
		dAtA[i] = 0x10
	}
	if m.Tp != 0 {
		i = encodeVarintTest(dAtA, i, uint64(m.Tp))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *TestBinlogRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TestBinlogRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TestBinlogRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Gtid != 0 {
		i = encodeVarintTest(dAtA, i, uint64(m.Gtid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTest(dAtA []byte, offset int, v uint64) int {
	offset -= sovTest(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Record) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Tp != 0 {
		n += 1 + sovTest(uint64(m.Tp))
	}
	if m.SchemaVer != 0 {
		n += 1 + sovTest(uint64(m.SchemaVer))
	}
	if m.Tid != 0 {
		n += 1 + sovTest(uint64(m.Tid))
	}
	if m.Gtid != 0 {
		n += 1 + sovTest(uint64(m.Gtid))
	}
	if m.Pk != 0 {
		n += 1 + sovTest(uint64(m.Pk))
	}
	if m.StartTs != 0 {
		n += 1 + sovTest(uint64(m.StartTs))
	}
	if m.Err != nil {
		l = m.Err.Size()
		n += 1 + l + sovTest(uint64(l))
	}
	return n
}

func (m *TestBinlogRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Gtid != 0 {
		n += 1 + sovTest(uint64(m.Gtid))
	}
	return n
}

func sovTest(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTest(x uint64) (n int) {
	return sovTest(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Record) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Record: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Record: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tp", wireType)
			}
			m.Tp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tp |= Record_RecordType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SchemaVer", wireType)
			}
			m.SchemaVer = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SchemaVer |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tid", wireType)
			}
			m.Tid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tid |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Gtid", wireType)
			}
			m.Gtid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Gtid |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pk", wireType)
			}
			m.Pk = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Pk |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTs", wireType)
			}
			m.StartTs = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartTs |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Err", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Err == nil {
				m.Err = &Error{}
			}
			if err := m.Err.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TestBinlogRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TestBinlogRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TestBinlogRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Gtid", wireType)
			}
			m.Gtid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Gtid |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTest(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTest
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTest
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTest
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTest
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTest        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTest          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTest = fmt.Errorf("proto: unexpected end of group")
)
